:- consult('01').

% a.)
%   ?- grandmother(liz, X).
%    T Call: grandmother(liz, _8452)
%    T Call: mother(liz, _9274)
%    T Call: parent(liz, _9274)
%    T Exit: parent(liz, tom)
%    T Call: female(liz)
%    T Exit: female(liz)
%    T Exit: mother(liz, tom)
%    T Call: parent(tom, _8452)
%    T Exit: parent(tom, sue)
%    T Exit: grandmother(liz, sue)
%   X = sue ;
%    T Redo: grandmother(liz, sue)
%    T Redo: parent(tom, sue)
%    T Exit: parent(tom, jim)
%    T Exit: grandmother(liz, jim)
%   X = jim ;
%    T Redo: grandmother(liz, jim)
%    T Redo: mother(liz, tom)
%    T Redo: parent(liz, tom)
%    T Exit: parent(liz, joe)
%    T Call: female(liz)
%    T Exit: female(liz)
%    T Exit: mother(liz, joe)
%    T Call: parent(joe, _8452)
%    T Fail: parent(joe, _8452)
%    T Fail: grandmother(liz, _8452)
%   false.


%  ?- offspring(ann, mary).
%   T Call: offspring(ann, mary)
%   T Call: parent(mary, ann)
%   T Fail: parent(mary, ann)
%   T Call: parent(_9500, ann)
%   T Exit: parent(mia, ann)
%   T Call: offspring(mia, mary)
%   T Call: parent(mary, mia)
%   T Exit: parent(mary, mia)
%   T Exit: offspring(mia, mary)
%   T Exit: offspring(ann, mary)
%  true ;
%   T Redo: offspring(ann, mary)
%   T Redo: offspring(mia, mary)
%   T Redo: parent(mary, mia)
%   T Fail: parent(mary, mia)
%   T Call: parent(_11102, mia)
%   T Exit: parent(mary, mia)
%   T Call: offspring(mary, mary)
%   T Call: parent(mary, mary)
%   T Fail: parent(mary, mary)
%   T Call: parent(_12704, mary)
%   T Fail: parent(_12704, mary)
%   T Fail: offspring(mary, mary)
%   T Redo: parent(mary, mia)
%   T Exit: parent(mike, mia)
%   T Call: offspring(mike, mary)
%   T Call: parent(mary, mike)
%   T Fail: parent(mary, mike)
%   T Call: parent(_12704, mike)
%   T Fail: parent(_12704, mike)
%   T Fail: offspring(mike, mary)
%   T Fail: offspring(mia, mary)
%   T Fail: offspring(ann, mary)
%  false.
